### ISSUE TITLE
The link to the reference paper for OpenTURNS is wrong.

### ISSUE THREAD

**Issue by mbaudin47** [openturns/www#60]
The current link to the OpenTURNS reference paper is currently arxiv:

https://github.com/openturns/www/blob/ef9096ff905fd9ac67f3d3ece4712bb8fc31f85f/index.html#L369

This was correct when the paper was unpublished, but since the paper is published, the correct link is:

https://rd.springer.com/referenceworkentry/10.1007%2F978-3-319-12385-1_64

**Comment by jschueller** [comment]
cmon you can just edit that file with the online editor
